[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bsmp"
version = "0.1.0"
description = "Python scripts and cmdlets for BSMP project"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Vladislav Krylov", email = "vvkrylov1@gmail.com" }]
dependencies = [
    "click"
]

[project.optional-dependencies]
dev = ["pytest"] # Right now no need for this 

[project.scripts]
bsmp = "bsmp.cli:cli"

[tool.setuptools.packages.find]
where = ["src"]
